[package]
name = "rpc_surgeon"
version = "0.1.0"
edition = "2026"

[depreqwest endencies]
reqwest = { workspace = true}
serde = { workspace = true}
serde_json = { workspace = true}
hex = { workspace = true}
sha3 = { workspace = true}

[lints]
workspace = true
